// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANORtGePgymHYBk5i9l5BJ6ntswygUNaU',
    appId: '1:954517734445:web:bc3286f0a9a6a9a7ed64a4',
    messagingSenderId: '954517734445',
    projectId: 'unify-85',
    authDomain: 'unify-85.firebaseapp.com',
    storageBucket: 'unify-85.firebasestorage.app',
    measurementId: 'G-DQFFM744NJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIMf2t9oCNCd5a1vlFWEfbEU3MSfKW_iY',
    appId: '1:954517734445:android:3bd47f4bed119a93ed64a4',
    messagingSenderId: '954517734445',
    projectId: 'unify-85',
    storageBucket: 'unify-85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWBP0mSUe_Onm3UL7_AdgEImVTx1WB3-0',
    appId: '1:954517734445:ios:fe60be6bb6040ad2ed64a4',
    messagingSenderId: '954517734445',
    projectId: 'unify-85',
    storageBucket: 'unify-85.firebasestorage.app',
    iosBundleId: 'com.example.unify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWBP0mSUe_Onm3UL7_AdgEImVTx1WB3-0',
    appId: '1:954517734445:ios:fe60be6bb6040ad2ed64a4',
    messagingSenderId: '954517734445',
    projectId: 'unify-85',
    storageBucket: 'unify-85.firebasestorage.app',
    iosBundleId: 'com.example.unify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANORtGePgymHYBk5i9l5BJ6ntswygUNaU',
    appId: '1:954517734445:web:a8ce04cb9cc1c378ed64a4',
    messagingSenderId: '954517734445',
    projectId: 'unify-85',
    authDomain: 'unify-85.firebaseapp.com',
    storageBucket: 'unify-85.firebasestorage.app',
    measurementId: 'G-61KJ0ZZLQG',
  );

}